travis:
  secure:
    BINSTAR_TOKEN: nmyipKlANeyprNW/WI5cUMd0SmGp8KqiGbBGx1ZM7n8QFe0QPNBvzAv5c//LepmnVz2yie1Exq7xOXUkUk7+ivf1Yu4aioVvFPWBO7KjeAMxdF9OJrOLvgY1+kFeEwmeZuIqUq6kl+7fmz7lWC50bPtkcaOq86lldD2VoquDueam40vCsuX9bR0qvRN6Zc5Djmr6aZkrNicpZ5XOUx37hAG1aOjdOgDI95wq9Z8ABQhNlxOxZGGiHAjqXjHYQzrGJO/lsZzmV8FNop7uoO3iboLdVlNPYlO/UljnqxGyr2Aphxy8vHhOkNXlIdN4yiFeTynbpfNAJGSMftDJt7SsMCpbJeNO/Eudtnj4tlASzkUjDpjjHL76hU5Nkh3OcNolkukZ17BkXpiAPBxE2dvrVyInp7YxxyklRpy69esAaChaSTdIGekNxP32RwUKdFDMq7MFfNhNTQMZg4l6L1vRfT3Xt+jdEZE8DZa1GpkpJOoatkJPIRmiCrNczgqYinTXZdEL5ZaXdz9jdX/A75DqCXSh27zL4/w0UKWMU7uttEiQ23wKGGfopyscQMnFw5ccwVR7QBCg63d8nmmoHbS/cUDbiDi6d0E1eyad29x5zPeieilP2DkplYyPCmTotbVtbqYTixLBliY9EwEFHr+40cWozGRptecpad5Kg5dmHDk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
