travis:
  secure:
    BINSTAR_TOKEN: bIUTSZ1QQDM01sR2fru//eJmmu0cq9Iz0xabubo8J5M4W+rViDxDiiL9wOEwmGswjaUydbOJqvRDGQm6YY5qFRvMOtJhgcGNCSu4GMnXCUdc7mrQQ/u/59kh6oJ7ATn3OgRh5dwQqErdLurYNKt/DVXVELpPaqsgRQjg76ImybayVxJDHdAbDA+puNRZ1UmQZ8bYHS2RcpvocJxuDp1t78vnp3BWxPe0ZyyHnFI+9TiACwIjnQ4SG+AkOSBU1qNfDc2KH3uNJ2VsmZKBoCB2VVaUmYoOf6zvqEA5wvRV/4DNn9vHbXXLpKlCmM1Ms5uoKOKHnOlx8FZ3LewcT2xR0N5L5Rii2mHZ/LHCtwwm23zSLeTNmsw7bd3yDrguQtzDFuU/fIpUoN9f4IGjrQ+kQ6yZHwLAIbWqSUT/WOculexkZOYsNUeykXjvZYp0cHRBG0BPDoFb0dncvsqKITSAyE5JYb1uqewE8qL03qqDkMUgHIUQwJYPUw7FrjF0Es3EERONAWPQqW0PaZhF5aPufOWr6q+0cTCM30bze5nrp0ilSCckGeowUueoJV7rfYcEKtDSWmG848G+U6N+58rGzPsixC0rsBhUbkvJ++kd4PSik26IPSgzD4DOQyrI9njQz4FJwviyUnLqIbshhZdv3uwiY9GWUihhiWo2y98z4Js=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
